<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="copyright">
	<div class="copyright content">
    <small><?= $block->escapeHtml($block->getCopyright()) ?></small>
	<span class="icon-link" title="Notre actualité sur Facebook"><a href="#" target="_blank" rel="noopener"><i class="fab fa-facebook-square"></i></a></span>
</div>
</div>

